import { describe, expect, it } from "vitest";
import * as Y from "yjs";
import {
  DEFAULT_FRAGMENT_NAME,
  exportPageYDoc,
  loadPageYDoc,
} from "./collab-persistence";
import type { PageRecord } from "@/server/db/repository";

describe("Real-Time Collaborative Multi-Client Concurrency", () => {
  const initialPage: PageRecord = {
    id: "page_concurrency_1",
    workspaceId: "ws_test_1",
    title: "Collaborative Roadmap",
    content: {
      type: "doc",
      content: [
        {
          type: "paragraph",
          content: [{ type: "text", text: "Initial" }],
        },
      ],
    },
    yjsState: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  it("should synchronize concurrent edits from 3 clients and converge deterministically", () => {
    // 1. Initialize server doc and 3 replica client docs
    const serverDoc = loadPageYDoc(initialPage);
    const serverState = exportPageYDoc(serverDoc);

    const clientA = new Y.Doc();
    const clientB = new Y.Doc();
    const clientC = new Y.Doc();

    Y.applyUpdate(clientA, serverState);
    Y.applyUpdate(clientB, serverState);
    Y.applyUpdate(clientC, serverState);

    // Verify initial states match
    const getFragmentText = (doc: Y.Doc): string => {
      const fragment = doc.getXmlFragment(DEFAULT_FRAGMENT_NAME);
      let result = "";
      for (let i = 0; i < fragment.length; i++) {
        const item = fragment.get(i);
        if (item instanceof Y.XmlElement) {
          for (let j = 0; j < item.length; j++) {
            const child = item.get(j);
            if (child instanceof Y.XmlText) {
              result += child.toString();
            }
          }
        }
      }
      return result;
    };

    expect(getFragmentText(clientA)).toBe("Initial");
    expect(getFragmentText(clientB)).toBe("Initial");
    expect(getFragmentText(clientC)).toBe("Initial");

    // 2. Client A, B, and C make concurrent edits without receiving updates yet
    // Client A: prepends "Hello " to the paragraph
    const fragmentA = clientA.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const pA = fragmentA.get(0) as Y.XmlElement;
    const textA = pA.get(0) as Y.XmlText;
    textA.insert(0, "Hello ");

    // Client B: appends " World" to the paragraph
    const fragmentB = clientB.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const pB = fragmentB.get(0) as Y.XmlElement;
    const textB = pB.get(0) as Y.XmlText;
    textB.insert(textB.length, " World");

    // Client C: adds a new taskList with a taskItem
    const fragmentC = clientC.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const taskList = new Y.XmlElement("taskList");
    fragmentC.push([taskList]);

    const taskItem = new Y.XmlElement("taskItem");
    taskItem.setAttribute("checked", "true");
    taskList.push([taskItem]);

    const taskText = new Y.XmlText();
    taskItem.push([taskText]);
    taskText.insert(0, "Complete Phase 9");

    // 3. Extract incremental updates generated by each client
    const updateA = Y.encodeStateAsUpdate(clientA, serverState);
    const updateB = Y.encodeStateAsUpdate(clientB, serverState);
    const updateC = Y.encodeStateAsUpdate(clientC, serverState);

    // 4. Exchange all updates between all replicas (simulating network delivery)
    Y.applyUpdate(serverDoc, updateA);
    Y.applyUpdate(serverDoc, updateB);
    Y.applyUpdate(serverDoc, updateC);

    Y.applyUpdate(clientA, updateB);
    Y.applyUpdate(clientA, updateC);

    Y.applyUpdate(clientB, updateA);
    Y.applyUpdate(clientB, updateC);

    Y.applyUpdate(clientC, updateA);
    Y.applyUpdate(clientC, updateB);

    // 5. Verify deterministic CRDT convergence
    const finalTextA = getFragmentText(clientA);
    const finalTextB = getFragmentText(clientB);
    const finalTextC = getFragmentText(clientC);
    const finalServerText = getFragmentText(serverDoc);

    expect(finalTextA).toBe("Hello Initial World");
    expect(finalTextB).toBe("Hello Initial World");
    expect(finalTextC).toBe("Hello Initial World");
    expect(finalServerText).toBe("Hello Initial World");

    // Verify taskList is present on all replicas
    expect(clientA.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);
    expect(clientB.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);
    expect(clientC.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);
    expect(serverDoc.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);

    // Verify persisted snapshot matches client state
    const persistedState = exportPageYDoc(serverDoc);
    const restoredDoc = new Y.Doc();
    Y.applyUpdate(restoredDoc, persistedState);
    expect(getFragmentText(restoredDoc)).toBe("Hello Initial World");
    expect(restoredDoc.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);
  });

  it("should handle offline local editing and merge cleanly upon reconnection", () => {
    // 1. Initial shared state
    const serverDoc = new Y.Doc();
    const fragmentServer = serverDoc.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const p = new Y.XmlElement("paragraph");
    fragmentServer.push([p]);

    const text = new Y.XmlText();
    p.push([text]);
    text.insert(0, "Base line");

    const initialSnapshot = exportPageYDoc(serverDoc);

    const onlineClient = new Y.Doc();
    const offlineClient = new Y.Doc();

    Y.applyUpdate(onlineClient, initialSnapshot);
    Y.applyUpdate(offlineClient, initialSnapshot);

    // 2. Online client receives edits while offline client is disconnected
    const onlineP = onlineClient.getXmlFragment(DEFAULT_FRAGMENT_NAME).get(0) as Y.XmlElement;
    const onlineText = onlineP.get(0) as Y.XmlText;
    onlineText.insert(0, "[Live] ");

    const onlineUpdate = Y.encodeStateAsUpdate(onlineClient, initialSnapshot);
    Y.applyUpdate(serverDoc, onlineUpdate);

    // 3. Offline client performs local edits while disconnected
    const offlineP = offlineClient.getXmlFragment(DEFAULT_FRAGMENT_NAME).get(0) as Y.XmlElement;
    const offlineText = offlineP.get(0) as Y.XmlText;
    offlineText.insert(offlineText.length, " [Offline Edit]");

    // 4. Offline client reconnects: exchanges updates with server
    const offlineUpdate = Y.encodeStateAsUpdate(offlineClient, initialSnapshot);
    const serverCatchupUpdate = Y.encodeStateAsUpdate(serverDoc, initialSnapshot);

    Y.applyUpdate(offlineClient, serverCatchupUpdate);
    Y.applyUpdate(serverDoc, offlineUpdate);
    Y.applyUpdate(onlineClient, offlineUpdate);

    // 5. Verify all nodes converged without losing either user's edits
    const expected = "[Live] Base line [Offline Edit]";

    const getFirstParagraphText = (doc: Y.Doc) => {
      const fragment = doc.getXmlFragment(DEFAULT_FRAGMENT_NAME);
      const elem = fragment.get(0) as Y.XmlElement;
      return (elem.get(0) as Y.XmlText).toString();
    };

    expect(getFirstParagraphText(serverDoc)).toBe(expected);
    expect(getFirstParagraphText(onlineClient)).toBe(expected);
    expect(getFirstParagraphText(offlineClient)).toBe(expected);
  });

  it("should preserve formatting marks during concurrent edits", () => {
    const docA = new Y.Doc();
    const fragmentA = docA.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const pA = new Y.XmlElement("paragraph");
    fragmentA.push([pA]);

    const textA = new Y.XmlText();
    pA.push([textA]);
    textA.insert(0, "Bold text", { bold: {} });

    const state = exportPageYDoc(docA);

    const docB = new Y.Doc();
    Y.applyUpdate(docB, state);

    // Client A inserts italic text inside paragraph
    const pA_elem = fragmentA.get(0) as Y.XmlElement;
    const textA_elem = pA_elem.get(0) as Y.XmlText;
    textA_elem.insert(textA_elem.length, " and italic", { italic: {} });

    // Client B inserts a heading above
    const fragmentB = docB.getXmlFragment(DEFAULT_FRAGMENT_NAME);
    const heading = new Y.XmlElement("heading");
    heading.setAttribute("level", "1");
    fragmentB.insert(0, [heading]);

    const headingText = new Y.XmlText();
    heading.push([headingText]);
    headingText.insert(0, "Document Header");

    // Exchange updates
    const updateA = Y.encodeStateAsUpdate(docA, state);
    const updateB = Y.encodeStateAsUpdate(docB, state);

    Y.applyUpdate(docA, updateB);
    Y.applyUpdate(docB, updateA);

    expect(docA.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);
    expect(docB.getXmlFragment(DEFAULT_FRAGMENT_NAME).length).toBe(2);

    const hA = docA.getXmlFragment(DEFAULT_FRAGMENT_NAME).get(0) as Y.XmlElement;
    const hB = docB.getXmlFragment(DEFAULT_FRAGMENT_NAME).get(0) as Y.XmlElement;
    expect(hA.nodeName).toBe("heading");
    expect(hB.nodeName).toBe("heading");
    expect((hA.get(0) as Y.XmlText).toString()).toBe("Document Header");
    expect((hB.get(0) as Y.XmlText).toString()).toBe("Document Header");
  });
});
